import AppKit

@MainActor protocol ClipboardReading {
    var changeCount: Int { get }
    func readText() -> String?
}

@MainActor struct SystemClipboard: ClipboardReading {
    let board: NSPasteboard
    private let sourceIsOwnApp: () -> Bool
    init(board: NSPasteboard = .general, sourceIsOwnApp: @escaping () -> Bool = {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier == Bundle.main.bundleIdentifier
    }) {
        self.board = board
        self.sourceIsOwnApp = sourceIsOwnApp
    }
    var changeCount: Int { board.changeCount }
    func readText() -> String? {
        let blocked = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                       "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
        guard !blocked.contains(where: { board.types?.contains(NSPasteboard.PasteboardType($0)) == true }),
              board.types?.contains(.fileURL) != true, !sourceIsOwnApp() else { return nil }
        return board.string(forType: .string)
    }
}

@MainActor final class ClipboardMonitor {
    private let reader: any ClipboardReading
    private let filter: (String) -> String?
    private var timer: Timer?
    private var lastCount = 0
    private var pendingCount: Int?
    private var duplicates = ClipboardDuplicates()
    private(set) var enabled = false
    var onChange: (() -> Void)?
    var onCandidate: ((String) -> Void)?

    init(reader: any ClipboardReading = SystemClipboard(), filter: @escaping (String) -> String? = { ClipboardPolicy.candidate($0) }) {
        self.reader = reader
        self.filter = filter
    }

    func start(schedule: Bool = true) {
        guard !enabled else { return }
        enabled = true
        // Never read the clipboard that existed before opt-in or launch.
        lastCount = reader.changeCount
        pendingCount = nil
        if schedule {
            let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated { self?.poll() }
            }
            RunLoop.main.add(timer, forMode: .common)
            self.timer = timer
        }
    }

    func stop() {
        enabled = false
        timer?.invalidate()
        timer = nil
        pendingCount = nil
        duplicates = ClipboardDuplicates()
    }

    func poll() {
        guard enabled else { return }
        let count = reader.changeCount
        if count != lastCount {
            lastCount = count
            pendingCount = count
            onChange?()
            return
        }
        guard pendingCount == count else { return }
        pendingCount = nil
        guard let raw = reader.readText(), reader.changeCount == count,
              let text = filter(raw), duplicates.accept(text) else { return }
        onCandidate?(text)
    }
}
